fix(rknn-bench): specify inputs=['\''data'\''] in load_onnx to fix dynamic batch dim
ResNet50-v2-7.onnx has a dynamic batch dimension named '\''N'\''.
rknn-toolkit2 2.3.2 requires both '\''inputs'\'' (tensor names) and
'\''input_size_list'\'' to override dynamic shapes; input_size_list alone
is not sufficient.

Error was:
  ValueError: The input shape ['\''N'\'', 3, 224, 224] of '\''data'\'' is not support!
  Please set the '\''inputs'\'' / '\''input_size_list'\'' parameters of '\''rknn.load_onnx'\''